// Auto generated by Craby. DO NOT EDIT.
#import "CxxCrabySha256Module.hpp"

#import <ReactCommon/CxxTurboModuleUtils.h>

@interface CrabySha256ModuleProvider : NSObject
@end

@implementation CrabySha256ModuleProvider
+ (void)load {
  facebook::react::registerCxxModuleToGlobalModuleMap(
      craby::crabysha256::CxxCrabySha256Module::kModuleName,
      [](std::shared_ptr<facebook::react::CallInvoker> jsInvoker) {
      return std::make_shared<craby::crabysha256::CxxCrabySha256Module>(jsInvoker);
      });
}
@end
