// Auto generated by Craby. DO NOT EDIT.
#[rustfmt::skip]
use crate::craby_sha_256_impl::*;
use crate::generated::*;

use bridging::*;

#[cxx::bridge(namespace = "craby::bridging")]
pub mod bridging {




    extern "Rust" {
        type CrabySha256;

        #[cxx_name = "createCrabySha256"]
        fn create_craby_sha_256(id: usize) -> Box<CrabySha256>;

        #[cxx_name = "digest"]
        fn craby_sha_256_digest(it_: &mut CrabySha256, data: &str) -> Result<String>;
    }

}

fn create_craby_sha_256(id: usize) -> Box<CrabySha256> {
    Box::new(CrabySha256::new(id))
}

fn craby_sha_256_digest(it_: &mut CrabySha256, data: &str) -> Result<String, anyhow::Error> {
    catch_panic!({
        let ret = it_.digest(data);
        ret
    })
}
