// Auto generated by Craby. DO NOT EDIT.
// Hash: a3b76376dd455c3f
#[rustfmt::skip]
use crate::ffi::bridging::*;
use crate::context::*;
use crate::types::*;

pub trait CrabySha256Spec {
    fn new(ctx: Context) -> Self;
    fn id(&self) -> usize;
    fn digest(&mut self, data: &str) -> String;
}
