// Auto generated by Craby. DO NOT EDIT.
#include <CxxCrabySha256Module.hpp>
#include <ReactCommon/CxxTurboModuleUtils.h>
#include <jni.h>

jint JNI_OnLoad(JavaVM *vm, void *reserved) {
  facebook::react::registerCxxModuleToGlobalModuleMap(
    craby::crabysha256::CxxCrabySha256Module::kModuleName,
    [](std::shared_ptr<facebook::react::CallInvoker> jsInvoker) {
      return std::make_shared<craby::crabysha256::CxxCrabySha256Module>(jsInvoker);
    });
  return JNI_VERSION_1_6;
}

extern "C"
JNIEXPORT void JNICALL
Java_com_crabysha256_CrabySha256Package_nativeSetDataPath(JNIEnv *env, jclass clazz, jstring jDataPath) {
  auto dataPath = std::string(env->GetStringUTFChars(jDataPath, nullptr));
  craby::crabysha256::CxxCrabySha256Module::dataPath = dataPath;
}
