// Auto generated by Craby. DO NOT EDIT.
#include <CxxCrabySha256Module.hpp>

#include <jni.h>
#include <ReactCommon/CxxTurboModuleUtils.h>

jint JNI_OnLoad(JavaVM *vm, void *reserved) {
  facebook::react::registerCxxModuleToGlobalModuleMap(
    craby::crabysha256::CxxCrabySha256Module::kModuleName,
    [](std::shared_ptr<facebook::react::CallInvoker> jsInvoker) {
      return std::make_shared<craby::crabysha256::CxxCrabySha256Module>(jsInvoker);
    });
  return JNI_VERSION_1_6;
}
